name: clicli_dark
description: CliCli Dark. clicli 纯黑.

version: 2.8.1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

  flutter_markdown: any
  url_launcher: any
  flutter_downloader: any
  path_provider: any
  flutter_flexible_toast: any
  shared_preferences: any
  event_bus: any
  music_volume: any
  package_info: any
  cached_network_image: any
  jpush_flutter: any
  webview_flutter: any

  dlna: any
  better_player:
    git: https://github.com/shiyiya/betterplayer.git
    # path: ../betterplayer/

  #  open_iconic_flutter: '>=0.3.0 <0.4.0'
  #  wakelock: '>=0.1.2 <0.2.0'
  #  flutter_widgets: ^0.1.12
  #  pedantic: ^1.8.0
  #  meta: ^1.0.5
  #  flutter_widget_from_html_core: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/loading.gif
    - assets/error.png
    - assets/login_bg.webp
