name: clicli_dark
description: CliCli Dark. clicli 纯黑.

version: 2.0.0+8

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

  flutter_markdown: any
  url_launcher: any
  flutter_downloader: any
  path_provider: any
  flutter_flexible_toast: any
  shared_preferences: any
  event_bus: any
  music_volume: any
  package_info: any
  cached_network_image: any
  jpush_flutter: any
  flutter_umplus: any

  # chewie
  video_player: '>=0.10.0 <2.0.0'
  screen: any
  open_iconic_flutter: any
  auto_orientation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/loading.gif
    - assets/error.png
