name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get

    - name: run tests
      uses: steebchen/flutter@v1.0.0
      with:
        args: test

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk -v --release --target-platform android-arm
    - name: Set Git Config
      run: git config --global user.name ${{ secrets.GIT_USER_NAME }} &&  git config --global user.email ${{ secrets.GIT_EMAL }}
    - name: Clone and push apk to clicli.me
      run: git clone https://${{ secrets.GH_TOKEN }}@github.com/cliclitv/app.clicli.me.git && cd ./app.clicli.me && mv build/app/outputs/apk/release/app-release.apk ./ && git add -A && git commit -m 'update release By TravisCI With Build ${TRAVIS_BUILD_NUMBER}' &&  git push -f https://${{ secrets.GH_TOKEN }}@github.com/cliclitv/app.clicli.me.git
      
